### ISSUE TITLE
Missing schema for PersonReferenceFormatter

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_content#634]
### Problem

The field formatter `oe_content_sub_entity_person_reference_formatter` is missing schema for the field formatter settings.

I encountered the issue when trying to import config that uses the field formatter during a kernel test.

```
1) Drupal\Tests\oe_whitelabel_agenda\Kernel\AgendaRenderTest::testRendering
Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_view_display.oe_agenda_session.oe_default.default with the following errors:
core.entity_view_display.oe_agenda_session.oe_default.default:content.oe_session_moderators.settings.label_only missing
schema,
core.entity_view_display.oe_agenda_session.oe_default.default:content.oe_session_moderators.settings.rel missing
schema,
core.entity_view_display.oe_agenda_session.oe_default.default:content.oe_session_moderators.settings.target missing schema 
```

### Proposed solution

The schema for the formatter settings should be added to [oe_content_sub_entity_person.schema.yml ](https://github.com/openeuropa/oe_content/blob/4.x/modules/oe_content_sub_entity/modules/oe_content_sub_entity_person/config/schema/oe_content_sub_entity_person.schema.yml)similar to the [authors reference](https://github.com/openeuropa/oe_content/blob/4.x/modules/oe_content_sub_entity/modules/oe_content_sub_entity_author/config/schema/oe_content_sub_entity_author.schema.yml#L15-L27) field.

```
field.formatter.settings.oe_content_sub_entity_person_reference_formatter:
  type: mapping
  label: 'Person reference field formatter settings'
  mapping:
    label_only:
      type: boolean
      label: 'Display as label'
    rel:
      type: string
      label: 'Add rel "nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'
```
